// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77nqHVQZXZFAJJyUPF6LpPPw9mT4R5NI',
    appId: '1:213767770039:web:9c265f365b39d031cf2232',
    messagingSenderId: '213767770039',
    projectId: 'fluttertask-817f8',
    authDomain: 'fluttertask-817f8.firebaseapp.com',
    storageBucket: 'fluttertask-817f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzOXc-tbyl0s3Fk1n8xa_uM5dfXr9qiyA',
    appId: '1:213767770039:android:15475c24bb46f40bcf2232',
    messagingSenderId: '213767770039',
    projectId: 'fluttertask-817f8',
    storageBucket: 'fluttertask-817f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgN9_8WYa6q4NpnpCKAvoODAuJTlmG1Nc',
    appId: '1:213767770039:ios:d50b5c33aa3caecbcf2232',
    messagingSenderId: '213767770039',
    projectId: 'fluttertask-817f8',
    storageBucket: 'fluttertask-817f8.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgN9_8WYa6q4NpnpCKAvoODAuJTlmG1Nc',
    appId: '1:213767770039:ios:d50b5c33aa3caecbcf2232',
    messagingSenderId: '213767770039',
    projectId: 'fluttertask-817f8',
    storageBucket: 'fluttertask-817f8.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB77nqHVQZXZFAJJyUPF6LpPPw9mT4R5NI',
    appId: '1:213767770039:web:ced0f8e3d51bf333cf2232',
    messagingSenderId: '213767770039',
    projectId: 'fluttertask-817f8',
    authDomain: 'fluttertask-817f8.firebaseapp.com',
    storageBucket: 'fluttertask-817f8.appspot.com',
  );
}
